(local plugin (. (require :lib.lazy) :plugin))

;; Catppuccin Mocha is defined locally so the editor does not depend on an
;; external colorscheme plugin. Keep this adapter aligned with the canonical
;; palette in features.theme-catppuccin-mocha.
(plugin :LazyVim/LazyVim
        {:opts
         {:colorscheme
          (fn []
            (local bg "#1E1E2E")
            (local surface "#313244")
            (local surface-highlight "#45475A")
            (local fg "#CDD6F4")
            (local subtext "#A6ADC8")
            (local muted "#6C7086")
            (local red "#F38BA8")
            (local peach "#FAB387")
            (local yellow "#F9E2AF")
            (local green "#A6E3A1")
            (local teal "#94E2D5")
            (local blue "#89B4FA")
            (local lavender "#B4BEFE")
            (local mauve "#CBA6F7")
            (local pink "#F5C2E7")
            (vim.cmd "highlight clear")
            (vim.cmd "set termguicolors")
            (vim.api.nvim_set_hl 0 :Normal {:fg fg :bg bg})
            (vim.api.nvim_set_hl 0 :NormalFloat {:fg fg :bg surface})
            (vim.api.nvim_set_hl 0 :Comment {:fg muted :italic true})
            (vim.api.nvim_set_hl 0 :Constant {:fg peach})
            (vim.api.nvim_set_hl 0 :String {:fg green})
            (vim.api.nvim_set_hl 0 :Number {:fg peach})
            (vim.api.nvim_set_hl 0 :Boolean {:fg mauve :bold true})
            (vim.api.nvim_set_hl 0 :Identifier {:fg fg})
            (vim.api.nvim_set_hl 0 :Function {:fg blue :bold true})
            (vim.api.nvim_set_hl 0 :Statement {:fg mauve :bold true})
            (vim.api.nvim_set_hl 0 :Keyword {:fg mauve :bold true})
            (vim.api.nvim_set_hl 0 :Type {:fg yellow})
            (vim.api.nvim_set_hl 0 :Special {:fg pink})
            (vim.api.nvim_set_hl 0 :CursorLine {:bg surface})
            (vim.api.nvim_set_hl 0 :CursorLineNr {:fg lavender :bold true})
            (vim.api.nvim_set_hl 0 :LineNr {:fg muted})
            (vim.api.nvim_set_hl 0 :Visual {:bg surface-highlight})
            (vim.api.nvim_set_hl 0 :Search {:fg bg :bg yellow})
            (vim.api.nvim_set_hl 0 :IncSearch {:fg bg :bg peach})
            (vim.api.nvim_set_hl 0 :Pmenu {:fg fg :bg surface})
            (vim.api.nvim_set_hl 0 :PmenuSel {:fg fg :bg surface-highlight :bold true})
            (vim.api.nvim_set_hl 0 :StatusLine {:fg fg :bg surface})
            (vim.api.nvim_set_hl 0 :StatusLineNC {:fg subtext :bg bg})
            (vim.api.nvim_set_hl 0 :WinSeparator {:fg muted})
            (vim.api.nvim_set_hl 0 :Title {:fg mauve :bold true})
            (vim.api.nvim_set_hl 0 :ErrorMsg {:fg bg :bg red :bold true})
            (vim.api.nvim_set_hl 0 :WarningMsg {:fg bg :bg peach})
            (vim.api.nvim_set_hl 0 :DiagnosticError {:fg red})
            (vim.api.nvim_set_hl 0 :DiagnosticWarn {:fg peach})
            (vim.api.nvim_set_hl 0 :DiagnosticInfo {:fg blue})
            (vim.api.nvim_set_hl 0 :DiagnosticHint {:fg teal})
            (vim.api.nvim_set_hl 0 "@variable" {:fg fg})
            (vim.api.nvim_set_hl 0 "@function" {:fg blue :bold true})
            (vim.api.nvim_set_hl 0 "@keyword" {:fg mauve :bold true})
            (vim.api.nvim_set_hl 0 "@string" {:fg green})
            (vim.api.nvim_set_hl 0 "@type" {:fg yellow})
            (vim.api.nvim_set_hl 0 "@constant" {:fg peach}))}})
