;; Evaluate the installed configuration using the pinned Guix and Asahi channels.
(use-modules (engstrand asahi)
             (engstrand bootloader)
             (engstrand desktop)
             (asahi guix systems desktop)
             (gnu)
             (gnu home)
             (gnu home services)
             (gnu services base)
             (gnu services guix)
             (gnu services shepherd)
             (gnu services xorg)
             (gnu system shadow)
             (gnu system uuid)
             (guix channels)
             (guix gexp)
             (guix packages)
             (ice-9 textual-ports)
             (srfi srfi-1))

(define (check value message)
  (unless value (error message)))
(define channels (primitive-load (cadr (command-line))))
(define os (primitive-load "desktop/system.scm"))
(define base
  (make-base-os #:root-uuid "c4f25409-b1a5-4ef0-8ac9-8e75f011668c"
                #:esp-uuid "5CDF-1DF4" #:channels channels))
(define services (operating-system-services os))
(define (find-service name)
  (find (lambda (s) (eq? name (service-type-name (service-kind s)))) services))
(define (accounts system)
  (map (lambda (user) (list (user-account-name user) (user-account-uid user)
                           (user-account-home-directory user) (user-account-password user)))
       (operating-system-users system)))

(check (equal? '("guix" "asahi")
               (map (compose symbol->string channel-name) channels))
       "Unexpected channels")
(check (every (lambda (c) (and (= 40 (string-length (channel-commit c)))
                               (channel-introduction c))) channels)
       "Unpinned or unauthenticated channel")
(check (equal? (map (lambda (c) (cons (channel-name c) (channel-commit c))) channels)
               (map (lambda (c) (cons (channel-name c) (channel-commit c)))
                    (guix-configuration-channels (service-value (find-service 'guix)))))
       "System changed pinned daemon channels")
(for-each
 (lambda (mount uuid)
   (let ((fs (find (lambda (fs) (string=? mount (file-system-mount-point fs)))
                   (operating-system-file-systems os))))
     (check (and fs (string-ci=? uuid (uuid->string (file-system-device fs))))
            "Filesystem identity changed")))
 '("/" "/boot/efi") '("c4f25409-b1a5-4ef0-8ac9-8e75f011668c" "5CDF-1DF4"))
(check (equal? "btrfs" (file-system-type (find (lambda (fs)
                                                 (string=? "/" (file-system-mount-point fs)))
                                               (operating-system-file-systems os))))
       "Internal root must be Btrfs")
(check (equal? '("/boot/efi")
               (bootloader-configuration-targets (operating-system-bootloader os)))
       "Wrong bootloader target")
(check (eq? m1n1-u-boot-grub-bootloader-os-prepare
            (bootloader-configuration-bootloader (operating-system-bootloader os)))
       "Missing patched bootloader")
(check (let* ((patch (car (origin-patches (package-source asahi-u-boot-os-prepare))))
              (module-dir (dirname (search-path %load-path "engstrand/bootloader.scm")))
              (patch-path (string-append module-dir "/u-boot-xhci-dwc3-os-prepare.patch")))
         (and (local-file? patch)
              (string-suffix? "u-boot-xhci-dwc3-os-prepare.patch" (local-file-file patch))
              (string-contains (call-with-input-file patch-path get-string-all)
                               "DM_FLAG_OS_PREPARE")))
       "Patched U-Boot must retain the OS_PREPARE patch")
(check (member "uas" (operating-system-initrd-modules os)) "Missing UAS initrd support")
(check (eq? (operating-system-kernel base) (operating-system-kernel os))
       "Desktop changed the kernel")
(check (equal? (operating-system-initrd-modules base) (operating-system-initrd-modules os))
       "Desktop changed the initrd")
(check (equal? (operating-system-user-kernel-arguments base)
               (operating-system-user-kernel-arguments os))
       "Desktop changed kernel arguments")
(check (equal? (accounts base) (accounts os)) "Desktop changed accounts")
(check (every (lambda (name)
                (let ((user (find (lambda (u) (string=? name (user-account-name u)))
                                  (operating-system-users os))))
                  (and user (not (user-account-password user)))))
              '("root" "engstrand"))
       "Passwords must remain outside the store")
(check (not (member "guest" (map user-account-name (operating-system-users os))))
       "Guest account leaked")
(for-each (lambda (name) (check (find-service name) "Missing system service"))
          '(asahi-firmware asahi-substitutes speakersafetyd rtkit sddm
            network-manager iwd guix-home backlight-udev-rules
            familiar-keyd familiar-keyd-config familiar-uinput screen-locker))
(check (not (find-service 'openssh)) "SSH must remain disabled")
(let ((packages (map package-name (operating-system-packages os))))
  (for-each (lambda (name) (check (member name packages) "Missing system package"))
            '("hyprland" "flatpak" "keyd"))
  (for-each (lambda (name) (check (not (member name packages)) "Obsolete desktop package"))
            '("sway" "foot")))
(check (equal? '("engstrand") (map car (service-value (find-service 'guix-home))))
       "Wrong Home owner")
(let* ((home (cadar (service-value (find-service 'guix-home))))
       (kinds (map (compose service-type-name service-kind)
                   (home-environment-services home)))
       (home-packages (map package-name (home-environment-packages home))))
  (check (eq? home (primitive-load "desktop/home.scm"))
         "Standalone Home must share the system Home definition")
  (for-each (lambda (name) (check (member name home-packages) "Missing Home package"))
            '("pi-coding-agent" "herdr" "herdr-sesh" "herdr-tiny-fingers"
              "jjui" "github-cli" "babashka" "noctalia" "ghostty"))
  (for-each (lambda (name) (check (memq name kinds) "Missing Home service"))
            '(familiar-direct-home-links familiar-herdr-plugins home-dbus pipewire))
  (check (every (lambda (s) (memq s (home-environment-services home)))
                %asahi-desktop-home-services)
         "Desktop changed protected Asahi audio/D-Bus services")
  (fold-services (home-environment-services home) #:target-type home-activation-service-type))
(check (not (screen-locker-configuration-allow-empty-password?
             (service-value (find-service 'screen-locker))))
       "Locker must reject empty passwords")
(fold-services services #:target-type activation-service-type)
(fold-services services #:target-type shepherd-root-service-type)
(display "PASS: installed system, channels, storage, bootloader, accounts, audio and Home graph.\n")
