(use-modules (engstrand asahi)
             (engstrand bootloader)
             (engstrand desktop)
             (engstrand desktop-files)
             (asahi guix systems desktop)
             (engstrand packages)
             (gnu)
             (gnu home)
             (gnu home services)
             (gnu services base)
             (gnu services guix)
             (gnu services shepherd)
             (gnu services xorg)
             (gnu system shadow)
             (gnu system uuid)
             (guix channels)
             (guix gexp)
             (guix packages)
             (srfi srfi-1))

(define (check value message)
  (unless value (error message)))
(define channels (primitive-load (cadr (command-line))))
(define (make constructor)
  (constructor #:root-uuid "11111111-2222-3333-4444-555555555555"
               #:esp-uuid "1234-ABCD" #:channels channels))
(define base (make make-ssd-os))
(define os (make make-familiar-os))
(define btrfs-desktop
  (make-familiar-os #:root-uuid "11111111-2222-3333-4444-555555555555"
                    #:esp-uuid "1234-ABCD" #:channels channels
                    #:root-filesystem-type "btrfs"))
(define services (operating-system-services os))
(define (find-service name)
  (find (lambda (s) (eq? name (service-type-name (service-kind s)))) services))

(check (equal? "btrfs"
               (file-system-type
                (find (lambda (fs) (string=? "/" (file-system-mount-point fs)))
                      (operating-system-file-systems btrfs-desktop))))
       "Desktop constructor must forward the Btrfs root type")
(check (eq? (operating-system-kernel base) (operating-system-kernel os))
       "Desktop must not change the kernel")
(check (equal? (operating-system-initrd-modules base) (operating-system-initrd-modules os))
       "Desktop must preserve initrd/UAS")
(check (equal? (operating-system-user-kernel-arguments base) (operating-system-user-kernel-arguments os))
       "Desktop must preserve kernel arguments")
(check (equal? '("/boot/efi")
               (bootloader-configuration-targets (operating-system-bootloader os)))
       "Desktop must preserve boot target")
(check (eq? (bootloader-configuration-bootloader (operating-system-bootloader base))
            (bootloader-configuration-bootloader (operating-system-bootloader os)))
       "Desktop must preserve the OS_PREPARE-patched bootloader")
(for-each
  (lambda (mount uuid)
    (let ((fs (find (lambda (fs) (string=? mount (file-system-mount-point fs)))
                    (operating-system-file-systems os))))
      (check (string-ci=? uuid (uuid->string (file-system-device fs))) "Filesystem changed")))
  '("/" "/boot/efi") '("11111111-2222-3333-4444-555555555555" "1234-ABCD"))
(for-each (lambda (name) (check (find-service name) "Missing retained/new desktop service"))
          '(asahi-firmware speakersafetyd rtkit sddm network-manager iwd guix-home
            backlight-udev-rules familiar-keyd familiar-keyd-config familiar-uinput
            screen-locker))
(check (not (find-service 'openssh)) "Desktop must not enable SSH")
(define (accounts system)
  (map (lambda (user) (list (user-account-name user) (user-account-uid user)
                           (user-account-home-directory user) (user-account-password user)))
       (operating-system-users system)))
(check (equal? (accounts base) (accounts os)) "Desktop must not change account declarations")
(let ((names (map package-name (operating-system-packages os))))
  (for-each (lambda (name) (check (member name names) "Missing compositor/terminal/browser"))
            '("hyprland" "kitty" "flatpak" "neovim" "git" "keyd"
              "brightnessctl"))
  (check (member "emacs-no-x" (map package-name (home-environment-packages
                                                   (cadar (service-value (find-service 'guix-home))))))
         "Terminal-only Emacs must be a Home package")
  (check (member "parinfer-rust-emacs"
                 (map package-name (home-environment-packages
                                    (cadar (service-value (find-service 'guix-home))))))
         "Parinfer's native library must be a Home package")
  (for-each (lambda (name) (check (not (member name names)) "Sway fallback must be dropped"))
            '("sway" "foot" "ungoogled-chromium")))
(check (member "pi-coding-agent" (map package-name (home-environment-packages
                                                    (cadar (service-value (find-service 'guix-home))))))
       "Pi must be a Home package")
(let ((home-packages (map package-name
                          (home-environment-packages
                           (cadar (service-value (find-service 'guix-home)))))))
  (for-each (lambda (name)
              (check (member name home-packages)
                     "Missing Herdr plugin package"))
            '("herdr" "herdr-sesh" "herdr-tiny-fingers")))
(check (member "jjui" (map package-name (home-environment-packages
                                         (cadar (service-value (find-service 'guix-home))))))
       "jjui must be a Home package")
(check (member "github-cli" (map package-name (home-environment-packages
                                               (cadar (service-value (find-service 'guix-home))))))
       "GitHub CLI must be a Home package")
(check (member "babashka" (map package-name (home-environment-packages
                                             (cadar (service-value (find-service 'guix-home))))))
       "Babashka must be a Home package")
(check (member "noctalia" (map package-name (home-environment-packages
                                             (cadar (service-value (find-service 'guix-home))))))
       "Noctalia must be a Home package")
(check (member "ghostty" (map package-name (home-environment-packages
                                            (cadar (service-value (find-service 'guix-home))))))
       "Ghostty must be a Home package")
(let ((home-packages (map package-name
                          (home-environment-packages
                           (cadar (service-value (find-service 'guix-home)))))))
  (for-each (lambda (name)
              (check (member name home-packages)
                     "Missing migrated development package"))
            '("babashka" "cmake" "fennel" "ghostty" "gopls" "libnotify" "nixfmt"
              "noctalia" "shellcheck" "typst" "uv")))
(check (equal? channels (guix-configuration-channels (service-value (find-service 'guix))))
       "Desktop changed channel pins")
(check (equal? '("engstrand") (map car (service-value (find-service 'guix-home))))
       "Home ownership changed")
(let* ((home (cadar (service-value (find-service 'guix-home))))
       (kinds (map (compose service-type-name service-kind) (home-environment-services home))))
  (check (memq 'familiar-direct-home-links kinds)
         "Missing direct Home links")
  (check (memq 'familiar-herdr-plugins kinds)
         "Missing Herdr plugin activation")
  (check (memq 'home-dbus kinds) "Missing Home D-Bus")
  (check (memq 'pipewire kinds) "Missing Asahi Home audio")
  (check (every (lambda (s) (memq s (home-environment-services home)))
                %asahi-desktop-home-services)
         "Desktop must preserve the channel's exact audio/D-Bus services")
  (check (member "pi-coding-agent" (map package-name (home-environment-packages home)))
         "Pi must be a Home package")
  (check (member "herdr" (map package-name (home-environment-packages home)))
         "Herdr must be a Home package")
  (check (member "jjui" (map package-name (home-environment-packages home)))
         "jjui must be a Home package")
  (check (member "github-cli" (map package-name (home-environment-packages home)))
         "GitHub CLI must be a Home package")
  (fold-services (home-environment-services home) #:target-type home-activation-service-type))
(let ((locker (service-value (find-service 'screen-locker))))
  (check (not (screen-locker-configuration-allow-empty-password? locker))
         "Locker must reject empty passwords"))
(for-each (lambda (entry)
            (check (file-exists? (local-file-file (cadr entry))) "Missing Home source"))
          %desktop-home-files)
(for-each (lambda (entry)
            (check (and (string? (car entry)) (string? (cdr entry)))
                   "Missing direct Home source"))
          %desktop-direct-home-links)
(fold-services services #:target-type activation-service-type)
(fold-services services #:target-type shepherd-root-service-type)
(display "PASS: desktop services/Home graph, sources, Sway fallback, unchanged storage/kernel/audio/pins.\n")
