# Alias definitions migrated from Home Manager.
# Keep commands simple; Fish expands these functions on demand.

alias '...'='../..'
alias dc='cd'
alias cdd='cd $HOME/Downloads'

alias week='date +%V'
alias exe='chmod 755'
alias wa='which -a'

alias ls='ls --color=auto'
alias sl='ls --color=auto'
alias ll='ls -lh --color=auto'
alias l='ll'
alias la='ls -a --color=auto'
alias lla='l -a'

alias vi='nvim'
alias iv='nvim'
alias vim='nvim'

alias ga='git add'
alias gau='git add --all'
alias gauc='git add -u && git commit --amend --no-edit'
alias gac='git commit --amend --no-edit'
alias gc='git commit --message'
alias gca='git commit --all'
alias gcam='git commit --all --message'
alias gd='git diff'
alias gds='git diff --staged'
alias gdh='git diff head'
alias gl='git log --decorate --color --graph'
alias gla='git log --oneline --decorate --color --graph --all'
alias gs='git status'
alias gss='git status --short'
alias gchf='git for-each-ref --sort="-committerdate" --format="%(committerdate:relative) == %(refname:short)" refs/heads | fzf | cut -d" " -f5 | xargs -I branch git checkout branch'
alias gchr='git checkout (git branch --sort=-committerdate | fzf | xargs)'
alias gch='git checkout'
alias 'gch-'='git checkout -'
alias gb='git branch'
alias gf='git fetch'
alias gp='git push'
alias gpu='git push --set-upstream origin HEAD'
alias gpl='git pull'
alias gr='git restore'
alias grs='git restore --staged'
alias grh='git reset head~'
alias gchm='git_checkout_main_or_master'
alias gdm='git_diff_main_or_master'
alias grmain='git fetch origin main:main && git rebase main'
alias gcl='git clone'
alias gg='cd (git rev-parse --show-cdup)'

alias tree='tree -I node_modules'

alias bluetooth_airpods='bluetoothctl connect 74:77:86:19:BA:5A'
alias battery='cat /sys/class/power_supply/macsmc-battery/capacity'

alias paste='fish_clipboard_paste'
