background {
    monitor =
    color = rgba(1e1e2eff)
}
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2
    outer_color = rgba(cba6f7ff)
    inner_color = rgba(313244ff)
    font_color = rgba(cdd6f4ff)
    placeholder_text = Password
    position = 0, 0
    halign = center
    valign = center
}
