[ids]
*

[main]
capslock = overload(control, esc)
leftshift = overload(shift, S-9)
rightshift = overload(shift, S-0)
leftmeta = layer(cmd)
rightmeta = layer(cmd)
sleep = micmute

[cmd]
c = C-insert
v = S-insert
x = S-delete
z = C-z
a = C-a
s = C-s
f = C-f
w = C-w
q = C-q
n = C-n
t = C-t
r = C-r
backspace = macro(C-S-home 40ms delete)
shift+z = C-y
shift+t = C-S-t
1 = C-1
2 = C-2
3 = C-3
4 = C-4
5 = C-5
6 = C-6
7 = C-7
8 = C-8
9 = C-9
0 = C-0
h = left
j = down
k = up
l = right
d = M-d
u = M-u
shift+u = M-S-u
enter = M-enter
e = M-e
g = M-g
space = M-space

[alt]
backspace = C-backspace
left = C-left
right = C-right
shift+left = M-S-left
shift+right = M-S-right
